### PR TITLE
Use JDK's flatMap() method after the JDK bug referred by MoreStreams#…

### PR DESCRIPTION
**Pull request by bhchandra**
…flatten() has been fixed.

### CODE REVIEW

**Comment by bhchandra** [comment]
The [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8075939) has been resolved on 2018-01-24 and `flatMap `operation can now be safely used on infinite streams without loss of short-circuiting of terminal operations.

**Comment by jbduncan** [comment]
I don't believe it's backported to Java 8, though. Since AFAICT google/mug still targets Java 8, I think `MoreStreams#flatten` still needs to keep its current fix for this bug.

**Comment by bhchandra** [comment]
Yup, I realized it a couple of minutes after I created the PR, and hence closed it.
Thanks.

**Comment by bhchandra** [comment]
Looks like this issue was fixed in the latest release of Java 8, `jdk8u222`.

You can locate it in the release notes with identifier `S8075939`

Release notes : http://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-July/009840.html
Discussion in the mailing list : https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-June/009520.html

**Comment by bhchandra** [comment]
I have to update my fork with your latest changes.

**Pull request closed without merging**
